
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lab-3_9
 */
public class adminclass extends javax.swing.JFrame {

    /**
     * Creates new form adminclass
     */
    public adminclass() {
        initComponents();
        setSize(600, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        pfpassword = new javax.swing.JPasswordField();
        btlogin = new javax.swing.JButton();
        lbadminlogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbusername.setBackground(new java.awt.Color(102, 255, 204));
        lbusername.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lbusername.setForeground(new java.awt.Color(0, 102, 102));
        lbusername.setText("Username");
        getContentPane().add(lbusername);
        lbusername.setBounds(60, 140, 140, 50);

        lbpassword.setBackground(new java.awt.Color(102, 255, 204));
        lbpassword.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lbpassword.setForeground(new java.awt.Color(0, 102, 102));
        lbpassword.setText("Password");
        getContentPane().add(lbpassword);
        lbpassword.setBounds(60, 230, 120, 40);

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername);
        tfusername.setBounds(250, 140, 230, 40);

        pfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pfpassword);
        pfpassword.setBounds(250, 230, 230, 40);

        btlogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btlogin.setForeground(new java.awt.Color(255, 0, 0));
        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        getContentPane().add(btlogin);
        btlogin.setBounds(270, 310, 180, 60);

        lbadminlogin.setBackground(new java.awt.Color(153, 255, 255));
        lbadminlogin.setFont(new java.awt.Font("SimSun", 3, 48)); // NOI18N
        lbadminlogin.setForeground(new java.awt.Color(255, 51, 51));
        lbadminlogin.setText("Admin Login");
        getContentPane().add(lbadminlogin);
        lbadminlogin.setBounds(100, 40, 330, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed

        try {
            String username = tfusername.getText();
            String password = pfpassword.getText();
            ResultSet rs = DBLoader.executeQuery("select * from admin where username = '" + username + "' and password = '" + password + "'");

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login Successfull !!");
                Home obj = new Home(username);
            } else {
                JOptionPane.showMessageDialog(this, "Login failed");

            }
        } catch (SQLException ex) {
            Logger.getLogger(adminclass.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btloginActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void pfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlogin;
    private javax.swing.JLabel lbadminlogin;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbusername;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
