
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab-3_9
 */
public class cashlogin extends javax.swing.JFrame {

    /**
     * Creates new form cashlogin
     */
    public cashlogin() {
        initComponents();
        setSize(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();
        pfpassword = new javax.swing.JPasswordField();
        btlogin = new javax.swing.JButton();
        lbcash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbusername.setText("Username");
        getContentPane().add(lbusername);
        lbusername.setBounds(100, 100, 120, 50);

        lbpassword.setText("Password");
        getContentPane().add(lbpassword);
        lbpassword.setBounds(100, 190, 120, 50);
        getContentPane().add(tfuser);
        tfuser.setBounds(260, 100, 120, 40);
        getContentPane().add(pfpassword);
        pfpassword.setBounds(260, 200, 120, 40);

        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        getContentPane().add(btlogin);
        btlogin.setBounds(280, 300, 70, 30);

        lbcash.setText("Cashier Login");
        getContentPane().add(lbcash);
        lbcash.setBounds(190, 10, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
       
        String username = tfuser.getText();
        String pass = pfpassword.getText();
        if(username.equals("")||pass.equals("")){
            JOptionPane.showMessageDialog(rootPane, "All fields are required");
        }
        else{
            
            try {
                
                ResultSet rs = DBLoader.executeQuery("select * from Cashier where username='"+username+"' and password='"+pass+"'");
    
                if(rs.next()){
                    
                    cashhome ch = new cashhome(username);
                    ch.setVisible(true);
                    
                }
                else{
                    
                    JOptionPane.showMessageDialog(rootPane, "Wrong Credetials");
                    
                }
                
            } catch (Exception e) {
            }
            
        }
        
    }//GEN-LAST:event_btloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlogin;
    private javax.swing.JLabel lbcash;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbusername;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables
}
