
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lab-3_9
 */
public class cashier extends javax.swing.JFrame {

    ArrayList<cashiers> al = new ArrayList<>();
    MyModel tm;
    

    /**
     * Creates new form cashier
     */
    public cashier() {
        initComponents();
        setSize(1000, 600);
        setVisible(true);
        tm = new MyModel();
        jTable2.setModel(tm);
        getCashiers();

    }

    public void getCashiers(){
        al.clear();
        
        try {
            
            ResultSet rs = DBLoader.executeQuery("select * from Cashier");
            while(rs.next()){
                
                String cid = rs.getString("cid");
                String user = rs.getString("username");
                String password = rs.getString("password");
                
                al.add(new cashiers(cid, user, password));
                tm.fireTableDataChanged();
            }
            
        } catch (Exception e) {
        }
        
    }
    
    
    class MyModel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            //To change body of generated methods, choose Tools | Templates.
            return al.size();
        }

        @Override
        public int getColumnCount() {
//To change body of generated methods, choose Tools | Templates.
            return 3;
        }

        @Override
        public Object getValueAt(int i, int j) {
//To change body of generated methods, choose Tools | Templates.
            cashiers cat = al.get(i);
            if (j == 0) {
                return cat.cid;
            } else if (j == 1) {
                return cat.username;
            }else {
                return cat.password;
            }

        }

        @Override
        public String getColumnName(int j) {
            String col[] = {"CashierID", "Username", "Password"};

            //To change body of generated methods, choose Tools | Templates.
            return col[j];
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbusername = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        tfusername1 = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        lbcashier = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btdelete = new javax.swing.JButton();
        pfpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbusername.setBackground(new java.awt.Color(204, 0, 51));
        lbusername.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbusername.setForeground(new java.awt.Color(0, 204, 204));
        lbusername.setText("Username");
        getContentPane().add(lbusername);
        lbusername.setBounds(42, 135, 170, 60);

        lbpassword.setBackground(new java.awt.Color(204, 0, 51));
        lbpassword.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbpassword.setForeground(new java.awt.Color(0, 204, 204));
        lbpassword.setText("Password");
        getContentPane().add(lbpassword);
        lbpassword.setBounds(42, 236, 170, 50);

        tfusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusername1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername1);
        tfusername1.setBounds(290, 150, 159, 40);

        btadd.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btadd.setForeground(new java.awt.Color(204, 0, 0));
        btadd.setText("ADD");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd);
        btadd.setBounds(200, 340, 83, 37);

        lbcashier.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbcashier.setForeground(new java.awt.Color(255, 0, 0));
        lbcashier.setText("Cashier");
        getContentPane().add(lbcashier);
        lbcashier.setBounds(180, 40, 160, 60);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(521, 42, 411, 280);

        btdelete.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btdelete.setForeground(new java.awt.Color(153, 0, 0));
        btdelete.setText("DELETE");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete);
        btdelete.setBounds(611, 436, 127, 37);
        getContentPane().add(pfpassword);
        pfpassword.setBounds(290, 240, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add  String cat = tfcatname.getText();

        String username = tfusername1.getText();
        String password = pfpassword.getText();
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "All fields are required !!!");
        } else {
            

            ResultSet rs = DBLoader.executeQuery("select * from Cashier");
            try {
                rs.moveToInsertRow();
                rs.updateString("username", username);
                rs.updateString("password", password);

                rs.insertRow();
                JOptionPane.showMessageDialog(this, "Cashier added");
                getCashiers();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }


    }//GEN-LAST:event_btaddActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
       
       int select = jTable2.getSelectedRow();
       if(select<0){
           
           JOptionPane.showMessageDialog(rootPane, "No row selected");
       }
       else{
           
           try {
               String cid = al.get(select).cid;
               ResultSet rs = DBLoader.executeQuery("select * from Cashier where cid='"+cid+"'");
               if(rs.next()){
                   
                   rs.deleteRow();
                   JOptionPane.showMessageDialog(rootPane, "Cashier deleted");
                   getCashiers();
               }
               
           } catch (Exception e) {
           }
           
           
           
       }
       
    }//GEN-LAST:event_btdeleteActionPerformed

    private void tfusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusername1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbcashier;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JLabel lbusername;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfusername1;
    // End of variables declaration//GEN-END:variables
}
