
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab-3_9
 */
public class changepass extends javax.swing.JFrame {
String username;
    /**
     * Creates new form changepass
     */
    public changepass() {
        initComponents();
        setSize(700,600);
        setVisible(true);
    }
    public changepass(String username) {
        initComponents();
          this.username = username;
        tfusername.setText(username);
        tfusername.setFocusable(false);
        setSize(700,600);
        setVisible(true);
        
    }
           

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbchangepass = new javax.swing.JLabel();
        lbusername = new javax.swing.JLabel();
        lboldpass = new javax.swing.JLabel();
        lbnewpass = new javax.swing.JLabel();
        lbconfirmpass = new javax.swing.JLabel();
        btchangepass = new javax.swing.JButton();
        tfusername = new javax.swing.JTextField();
        pfoldpass = new javax.swing.JPasswordField();
        pfnewpass = new javax.swing.JPasswordField();
        pfconfirmpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbchangepass.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        lbchangepass.setForeground(new java.awt.Color(255, 51, 51));
        lbchangepass.setText("Change Password");
        getContentPane().add(lbchangepass);
        lbchangepass.setBounds(200, 30, 240, 60);

        lbusername.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbusername.setText("Username");
        getContentPane().add(lbusername);
        lbusername.setBounds(70, 110, 190, 50);

        lboldpass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lboldpass.setText("Old Password");
        getContentPane().add(lboldpass);
        lboldpass.setBounds(70, 190, 210, 50);

        lbnewpass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbnewpass.setText("New Password");
        getContentPane().add(lbnewpass);
        lbnewpass.setBounds(70, 270, 210, 50);

        lbconfirmpass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbconfirmpass.setText("Confirm Password");
        getContentPane().add(lbconfirmpass);
        lbconfirmpass.setBounds(70, 340, 230, 50);

        btchangepass.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        btchangepass.setForeground(new java.awt.Color(204, 51, 0));
        btchangepass.setText("Change Password");
        btchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchangepassActionPerformed(evt);
            }
        });
        getContentPane().add(btchangepass);
        btchangepass.setBounds(160, 430, 280, 60);

        tfusername.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        tfusername.setForeground(new java.awt.Color(0, 255, 255));
        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername);
        tfusername.setBounds(330, 110, 190, 40);

        pfoldpass.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        pfoldpass.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(pfoldpass);
        pfoldpass.setBounds(330, 190, 190, 40);

        pfnewpass.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        pfnewpass.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(pfnewpass);
        pfnewpass.setBounds(330, 270, 190, 40);

        pfconfirmpass.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        pfconfirmpass.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(pfconfirmpass);
        pfconfirmpass.setBounds(330, 350, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_tfusernameActionPerformed

    private void btchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchangepassActionPerformed
        // TODO add your handling code here:
        String oldpass = pfoldpass.getText();
        String newpass = pfnewpass.getText();
        String confirmpass = pfconfirmpass.getText();
                
        if(oldpass.isEmpty()|| newpass.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"All field are required");
        }
        else
        {
      
      
            
        if(newpass.equals(confirmpass))
        {
            try {
                          ResultSet rs=DBLoader.executeQuery("select * from admin where username='" + username + "' and password= '" + oldpass + "'");

                if(rs.next())
                {
                    rs.updateString("password",newpass);
                    rs.updateRow();
                    JOptionPane.showMessageDialog(this,"Password updated successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Invalid Old Password");
                }   } catch (SQLException ex) {
                ex.printStackTrace();
            }
        
        }
        else
        {
        JOptionPane.showMessageDialog(this,"New password and Confirm Password must match");
        }
        }
             
    }//GEN-LAST:event_btchangepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btchangepass;
    private javax.swing.JLabel lbchangepass;
    private javax.swing.JLabel lbconfirmpass;
    private javax.swing.JLabel lbnewpass;
    private javax.swing.JLabel lboldpass;
    private javax.swing.JLabel lbusername;
    private javax.swing.JPasswordField pfconfirmpass;
    private javax.swing.JPasswordField pfnewpass;
    private javax.swing.JPasswordField pfoldpass;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
