/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lab-3_9
 */
public class Home extends javax.swing.JFrame {
String username;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(600,600);
        setVisible(true);
                
    }
public Home(String username) {
        initComponents();
        this.username=username;
        lbuser.setText(username);
        setSize(600,500);
        setVisible(true);
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbhomepage = new javax.swing.JLabel();
        lbwelcome = new javax.swing.JLabel();
        lbuser = new javax.swing.JLabel();
        btchangepass = new javax.swing.JButton();
        btmanage = new javax.swing.JButton();
        btproduct = new javax.swing.JButton();
        btcashier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbhomepage.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbhomepage.setForeground(new java.awt.Color(204, 0, 0));
        lbhomepage.setText("HOME PAGE");
        getContentPane().add(lbhomepage);
        lbhomepage.setBounds(150, 30, 240, 40);

        lbwelcome.setBackground(new java.awt.Color(0, 51, 51));
        lbwelcome.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lbwelcome.setForeground(new java.awt.Color(0, 153, 0));
        lbwelcome.setText("WELCOME");
        getContentPane().add(lbwelcome);
        lbwelcome.setBounds(50, 100, 130, 40);

        lbuser.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lbuser.setForeground(new java.awt.Color(51, 204, 0));
        getContentPane().add(lbuser);
        lbuser.setBounds(200, 100, 300, 40);

        btchangepass.setBackground(new java.awt.Color(0, 255, 204));
        btchangepass.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btchangepass.setForeground(new java.awt.Color(0, 51, 153));
        btchangepass.setText("Change Password");
        btchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchangepassActionPerformed(evt);
            }
        });
        getContentPane().add(btchangepass);
        btchangepass.setBounds(140, 150, 250, 50);

        btmanage.setBackground(new java.awt.Color(0, 255, 204));
        btmanage.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btmanage.setForeground(new java.awt.Color(0, 51, 153));
        btmanage.setText("Manage Categories");
        btmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmanageActionPerformed(evt);
            }
        });
        getContentPane().add(btmanage);
        btmanage.setBounds(140, 220, 250, 50);

        btproduct.setBackground(new java.awt.Color(0, 255, 204));
        btproduct.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btproduct.setForeground(new java.awt.Color(0, 0, 153));
        btproduct.setText("Manage Products");
        btproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproductActionPerformed(evt);
            }
        });
        getContentPane().add(btproduct);
        btproduct.setBounds(140, 290, 250, 50);

        btcashier.setBackground(new java.awt.Color(0, 255, 204));
        btcashier.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btcashier.setForeground(new java.awt.Color(0, 0, 153));
        btcashier.setText("Manage Cashiers");
        btcashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcashierActionPerformed(evt);
            }
        });
        getContentPane().add(btcashier);
        btcashier.setBounds(140, 360, 250, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchangepassActionPerformed
        // TODO add your handling code here:
        changepass obj = new changepass(username);
    }//GEN-LAST:event_btchangepassActionPerformed

    private void btmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmanageActionPerformed
        // TODO add your handling code here:
        category obj = new category();
    }//GEN-LAST:event_btmanageActionPerformed

    private void btproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproductActionPerformed
        // TODO add your handling code here:
        product obj = new product();
    }//GEN-LAST:event_btproductActionPerformed

    private void btcashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcashierActionPerformed
        cashier obj=new cashier();
    }//GEN-LAST:event_btcashierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcashier;
    private javax.swing.JButton btchangepass;
    private javax.swing.JButton btmanage;
    private javax.swing.JButton btproduct;
    private javax.swing.JLabel lbhomepage;
    private javax.swing.JLabel lbuser;
    private javax.swing.JLabel lbwelcome;
    // End of variables declaration//GEN-END:variables
}
